### ISSUE TITLE
Версия программы

### ISSUE THREAD

**Issue by cyperdark** [SGezha/osu-Direct#13]
Добавить номер версии программы сюда: https://i.imgur.com/JMRtgQd.jpg

**Comment by uzervlad** [comment]
Изображение удалено, пожалуйста, залей ещё раз

**Comment by cyperdark** [comment]
https://i.imgur.com/leYDYJv.jpg

**Comment by uzervlad** [comment]
Done in [Version 2](/OctoDumb/osu-direct/tree/version2)
