### ISSUE TITLE
Сортировка выводимых карт

### ISSUE THREAD

**Issue by cyperdark** [SGezha/osu-Direct#3]
Добавить сортировку выводимых карт, по следующим критериям:
- Data
- Star
- Favorites
- Length
- Play count
- AR
- OD
- CS

**Comment by SGezha** [comment]
Щас будет 😎👍

**Comment by uzervlad** [comment]
> Щас будет

Может стоит отвечать немного формальнее? @SGezha

**Comment by SGezha** [comment]
Зачем ?
