### ISSUE TITLE
Вкладка с настройками

### ISSUE THREAD

**Issue by cyperdark** [SGezha/osu-Direct#4]
Добавить вкладку с найстройками, и на неё добавить следующее:
- Два списка с игнорируемыми картами:
	1) Игнорируемые карты добавленные в osu!direct'e.
	2) Список для добавления id карт, для их последующего восстановления.
- Регулятор громкости воспроизведение карты.
- Переключатель показа карт "Из списка восстановления".

P.s. Желательно добавить сюда: https://i.imgur.com/dS2AEkg.jpg

**Comment by uzervlad** [comment]
Немного не понял насчёт "списка для добавления id карт, для их последующего восстановления". Объясни, что ты имел ввиду.

**Comment by cyperdark** [comment]
> Немного не понял насчёт "списка для добавления id карт, для их последующего восстановления". Объясни, что ты имел ввиду.

Ну список где все id твоих карт из осу, он нужен для восстановления своих карт, в случае того если вдруг удалил все

**Comment by uzervlad** [comment]
Понял, мы подумаем над этой идеей

**Comment by uzervlad** [comment]
#11
